export default {
  INTEGRATOR_SAVE: "Integrator Saved Successfully.",
  INTEGRATOR_UPDATE: "Integrator Updated Successfully.",
  INTEGRATOR_DELETE: "Integrator Deleted Successfully.",
  INTEGRATOR_NOT_FOUND: "Integrator not found with the given ID.",
  INTEGRATOR_PATHPARAMETERS_ERROR: "Please provide Integrator ID.",
  GROUP_SAVE: "Group Saved Successfully.",
  GROUP_UPDATE: "Group Updated Successfully.",
  GROUP_DELETE: "Group Deleted Successfully.",
  GROUP_NOT_FOUND: "Group not found with the given ID.",
  GROUP_PATHPARAMETERS_ERROR: "Please provide Group ID.",
  SITE_SAVE: "Site Saved Successfully.",
  SITE_UPDATE: "Site Updated Successfully.",
  SITE_DELETE: "Site Deleted Successfully.",
  SITE_NOT_FOUND: "Site not found with the given ID.",
  SITE_PATHPARAMETERS_ERROR: "Please provide Site ID.",
  USER_SAVE: "User Saved Successfully.",
  USER_UPDATE: "User Updated Successfully.",
  USER_DELETE: "User Deleted Successfully.",
  USER_NOT_FOUND: "User not found with the given ID.",
  USER_PATHPARAMETERS_ERROR: "Please provide User ID.",
  CUSTOMER_SAVE: "Customer Saved Successfully.",
  CUSTOMER_UPDATE: "Customer Updated Successfully.",
  CUSTOMER_DELETE: "Customer Deleted Successfully.",
  CUSTOMER_NOT_FOUND: "Customer not found with the given ID.",
  CUSTOMER_PATHPARAMETERS_ERROR: "Please provide Customer ID.",
  CAMERA_SAVE: "Camera Saved Successfully.",
  CAMERA_UPDATE: "Camera Updated Successfully.",
  CAMERA_DELETE: "Camera Deleted Successfully.",
  CAMERA_NOT_FOUND: "Camera not found with the given ID.",
  CAMERA_PATHPARAMETERS_ERROR: "Please provide Camera ID.",
  SERVER_ERROR: "Internal Server Error occured.",
};
